### ISSUE TITLE
Syntax error while trying to start Near-core

### ISSUE THREAD

**Issue by anjing-puteh** [Xn2/Near-core#1]
Hi, I followed the instructions from readme but I'm getting this syntax error issue when I try to run index.js.

![error-nearcore](https://user-images.githubusercontent.com/9395742/177543083-4cc419f8-6762-450f-b327-da1a849503b6.jpg)

Is there any OS requirement to run Near-core? I'm currently running on Ubuntu 20.04.4.
Thanks fore creating the Near-core :)

**Comment by Xn2** [comment]
Hi :)

Can you send me the output of the `node -v` command ?

**Comment by anjing-puteh** [comment]
Hi thanks for the lightning-fast response, the initial node -v output was v10.xx,xx something and I realize the node I have is really old.

I manage to get it running after updating my node version to 16.15.1 and installing express. :)
Thanks for the guide and I'm sorry for the trouble caused.

**Comment by Xn2** [comment]
Aight, glad you could get it up and running :)

**Comment by anjing-puteh** [comment]
By the way, is the music_db.json the same format as A****a? 
As I have generated my own musicdb with some custom songs and removed songs.

**Comment by Xn2** [comment]
Yes, it is purposfully the same format. However, I use an external API to fetch song information in the frontend.

**Comment by anjing-puteh** [comment]
Ah okay, I guess I can use mine then.
Did a quick test just now and I'm getting some new error messages here:

![image](https://user-images.githubusercontent.com/9395742/177553466-f0f94d91-3d3d-460b-8def-9c0db67b2d25.png)

I haven't updated the music list with my custom yet, can this be the cause?

**Comment by Xn2** [comment]
Can you tell me exactly when it crashes or what action causes the crash ?
Also, please make sure everything works before trying to add custom stuff :)

**Comment by Xn2** [comment]
Can you tell me what action causes the crash and when it crashes ? Also, please make sure everything is working correctly before adding custom stuff :)

**Comment by anjing-puteh** [comment]
So after doing some more tests in premium time mode, this is what I found:
- Previous error happens after I finish a song, happens to old or new songs.
- Near-core will crash when I end the game and try to save (Screenshot below).

![image](https://user-images.githubusercontent.com/9395742/177558367-f4345300-60ea-47aa-9f9a-291cb6d2c651.png)

**Comment by Xn2** [comment]
Interesting. What datecode are you running ?

**Comment by anjing-puteh** [comment]
I'm currently running on 2022062800, we can bring the conversation somewhere else I think :P

**Comment by Xn2** [comment]
Aight, hmu on Discord, Lyne#8499
